version: "3.7"

services:

  # bot
  douyintgbot:
    image: jwstar/douyintgbot
    network_mode: host
    container_name: douyintgbot
    restart: always
    environment:
      TZ: Asia/Shanghai
      #正式
      API_ID: 21153848
      API_HASH: bdcad7af6ab62608af2527b4cee20bcd
      BOT_TOKEN: 5913788955:AAEIP7M18RhAhSz2t2kCZDm31CxH19HJQFA
      CHANNEL_ID: -1001869610242

    deploy:
      resources:
        limits:
          cpus: '0.80'